### ISSUE TITLE
Общее заметки про структуру кода

### ISSUE THREAD

**Issue by WaldLumen** [BaldrProgrammer/userbot#1]
1. Писать код функций в мэйн файле - дичайший говнокод. В случае такого вот юзербота как у тебя куда более логично разбить функционал бота на несколько категорий и разместить функции по этим категориям. В качестве примера можно сделать несколько файлов в категории /src: group_management.py и passwords_manager.py внутри которых уже размещать основной код для них и просто импортировать в мейн файл. Это позволит добится большей удобочитаймости кода и в будущем более простой его масштабироемости.
2. Не храни app_id и api_hash в качестве переменных внутри кода. Для этого есть переменные окружения или на крайняк отдельный файл который ты не разместишь на гитхаб. Почему так делать не надо? Потому что есть скрипты которые парсят гитхаб и подменяют код твоего бота на вредоносный.
3. Переменные uid, cid излишни. Ты можешь просто прописывать message.chat.id там где у тебя стоят переменные и по факту станет лишь лучше так как программа будет потреблять меньше памяти не сохраняя эти значения.

**Comment by BaldrProgrammer** [comment]
1.  знаю. локаленс написан в нескольких файлах а тут мне было лень изначально продумывать что и куда писать, это первая версия которую я коммичу на гитхаб просто потому что.
2. тоже самое что и первое, те же причины. я использую .env(буду*)
3. мне удобнее с ними
